<div id="topnav">
    <ul>
        <li><a href="<?= $this->url(array('controller' => 'bug'), 'default', true) ?>">Issues</a></li>
        <? if ('guest' === $this->getRole()): ?>
        <li><a href="<?= $this->url(array('controller' => 'user'), 'default', true) ?>/user">Login/Register</a></li>
        <? else: ?>
            <? if ($this->checkAcl('bug', 'add')): ?>
        <li><a href="<?= $this->url(array('controller' => 'bug', 'action' => 'add'), 'default', true) ?>">Report an Issue</a></li>
            <? endif ?>
        <li>Logged in as <a href="<?= $this->url(array('controller' => 'user', 'action' => 'view'), 'default', true) ?>"><?= $this->user_name ?></a></li>
        <? endif ?>
    </ul>
</div>
